name: Vite Build CI

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.18.2 ]

    steps:

    - name: Checkout 🛎️
      uses: actions/checkout@v3

    - name: Setup Node.js ${{ matrix.node-version }} 🔨
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install pnpm 🔨
      run: npm i -g pnpm

    - name: Install npm packages 🔨
      run: pnpm i

    - name: Vite build 🗜️
      run: pnpm run build

    - name: Deploy to Gtihub Pages 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: pages
        folder: dist